version: '3' #docker version
services:
  www:
    build: 
      context: .
      dockerfile: Dockerfile
    image: yousocial:apache
    volumes:
      - "./:/var/www/html" #sync project dir with contanier web dir
    ports:
      - 80:80
      - 443:443 #for future ssl traffic
  
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=you.social
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 #equivalent to true
    volumes:
      - "./db:/docker-entrypoint-initdb.d" #sync persistent sql files with contianer
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306